[package]
name = "swiftnav-rs"
version = "0.1.0"
authors = ["Joseph Angelo <joseph.angelo@swift-nav.com>"]
edition = "2018"
description = "Low level GNSS decoding and positioning"
readme = "README.md"
repository = "https://github.com/swift-nav/swiftnav-rs"
license = "LGPL-3.0"


# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[build-dependencies]
bindgen = "0.55.1"
cmake = "0.1"
